slogan: "Yet another bootstrap theme."

theme: cerulean
inverse: inverse

menu:
  - title: 首页
    url:
    intro: "All the tags."
    icon: "fa fa-fire"
  - title: 文章
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: 招聘
    url: categories/hr/
    intro: "All the articles."
    icon: "fa fa-binoculars"
  - title: 求职
    url: categories/job/
    intro: "heroes"
    icon: "fa fa-bookmark"
  - title: 英雄榜
    url: categories/hr/
    intro: "heroes"
    icon: "fa fa-crosshairs"

links:
  - title: "属于北京前端的github"
    url: http://www.github.com/beijingjs
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "联盟群"
    url: http://jsfront.org
    intro: "中国最大前端联盟组织."
    icon: "fa fa-share"

widgets:
  - search
  - broadcast
  - category
  - tagcloud
  - links
  - recent_comments
  - recent_visitor

rss:
fancybox: true
favicon: favicon.ico
duoshuo_shortname: beijingjs

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: YYG5W2xNQTns7U8J3YqW

# share widgets
bdshare: true
# jiathis: true
